disabled-items:
  - "tnt"
  - "lava_bucket"
  - "lava"

block-place: true
block-use: true
block-pickup: true
block-command: true
remove-creative: true
show-message: true
message: "This item is disabled"
