disabled-items:
  - "tnt"
  - "46"
  - "lava_bucket"
  - "flint_and_steel"
  - "fire_charge"
  - "lava"
  - "water_bucket"

block-place: true
block-use: true
block-pickup: true
block-command: true
remove-creative: true
show-message: true
message: "This item is disabled"
